server:
  port: 8021

spring:
  application:
    name: stock-nacos
  cloud:
    nacos:
      server-addr: 10.10.10.176:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
      #        ephemeral: false #永久节点