server:
  port: 8030

spring:
  application:
    name: order-loadbalancer
  cloud:
    nacos:
#      server-addr: 10.10.10.176:8848
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP
#        ephemeral: false #永久节点